import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Design System Tokens (matching globals.css) ──
        'outline':                   '#767576',
        'on-surface-variant':        '#adaaab',
        'on-surface':                '#ffffff',
        'primary':                   '#a1ffc2',
        'primary-dim':               '#00ec90',
        'primary-fixed':             '#00fc9a',
        'primary-fixed-dim':         '#00ec90',
        'error':                     '#ff716c',
        'error-dim':                 '#d7383b',
        'error-container':           '#9f0519',
        'on-error-container':        '#ffa8a3',
        'secondary':                 '#feb700',
        'secondary-dim':             '#ecaa00',
        'secondary-container':       '#7c5800',
        'on-secondary-container':    '#fff6ee',
        'secondary-fixed':           '#ffc965',
        'secondary-fixed-dim':       '#feb700',
        'on-secondary':              '#533a00',
        'on-secondary-fixed':        '#463000',
        'on-secondary-fixed-variant':'#6b4b00',
        'tertiary':                  '#ff7257',
        'tertiary-dim':              '#ff7257',
        'tertiary-container':        '#fa4728',
        'tertiary-fixed':            '#ff937d',
        'tertiary-fixed-dim':        '#ff7c62',
        'on-tertiary':               '#470500',
        'on-tertiary-container':     '#000000',
        'on-tertiary-fixed':         '#380300',
        'on-tertiary-fixed-variant': '#750e00',
        'on-primary':                '#00643a',
        'on-primary-container':      '#005b34',
        'on-primary-fixed':          '#004627',
        'on-primary-fixed-variant':  '#00653b',
        'inverse-primary':           '#006d40',
        'surface':                   '#0e0e0f',
        'surface-dim':               '#0e0e0f',
        'surface-bright':            '#2c2c2d',
        'surface-container-lowest':  '#000000',
        'surface-container-low':     '#131314',
        'surface-container':         '#1a191b',
        'surface-container-high':    '#201f21',
        'surface-container-highest': '#262627',
        'surface-variant':           '#262627',
        'surface-tint':              '#a1ffc2',
        'on-background':             '#ffffff',
        'on-error':                  '#490006',
        'outline-variant':           '#484849',
        'inverse-surface':           '#fcf8f9',
        'inverse-on-surface':        '#565556',
        'background':                '#0e0e0f',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        mono:     ['JetBrains Mono', 'Fira Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
};

export default config;
